package secondhandtrade.paltform.model;

public class Bedroom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bedroom.b_no
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    private String bNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bedroom.name
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bedroom.b_no
     *
     * @return the value of bedroom.b_no
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public String getbNo() {
        return bNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bedroom.b_no
     *
     * @param bNo the value for bedroom.b_no
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public void setbNo(String bNo) {
        this.bNo = bNo == null ? null : bNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bedroom.name
     *
     * @return the value of bedroom.name
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bedroom.name
     *
     * @param name the value for bedroom.name
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}