package secondhandtrade.paltform.model;

import java.math.BigDecimal;
import java.util.Date;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.p_id
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    private String pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.p_name
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    private String pName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.num
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.type
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.description
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.u_id
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    private String uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.start_date
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.state
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.flag
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    private Integer flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.image
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    private String image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.p_id
     *
     * @return the value of product.p_id
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.p_id
     *
     * @param pId the value for product.p_id
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.p_name
     *
     * @return the value of product.p_name
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.p_name
     *
     * @param pName the value for product.p_name
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.num
     *
     * @return the value of product.num
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.num
     *
     * @param num the value for product.num
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.type
     *
     * @return the value of product.type
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.type
     *
     * @param type the value for product.type
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.description
     *
     * @return the value of product.description
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.description
     *
     * @param description the value for product.description
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.u_id
     *
     * @return the value of product.u_id
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public String getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.u_id
     *
     * @param uId the value for product.u_id
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.start_date
     *
     * @return the value of product.start_date
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.start_date
     *
     * @param startDate the value for product.start_date
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.state
     *
     * @return the value of product.state
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.state
     *
     * @param state the value for product.state
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.flag
     *
     * @return the value of product.flag
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.flag
     *
     * @param flag the value for product.flag
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.image
     *
     * @return the value of product.image
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.image
     *
     * @param image the value for product.image
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }
}