package secondhandtrade.paltform.model;

import java.math.BigDecimal;
import java.util.Date;

public class Trade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.t_id
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    private String tId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.u_id
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    private String uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.account
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    private BigDecimal account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.t_date
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    private Date tDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.state
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.flag
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.t_id
     *
     * @return the value of trade.t_id
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public String gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.t_id
     *
     * @param tId the value for trade.t_id
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public void settId(String tId) {
        this.tId = tId == null ? null : tId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.u_id
     *
     * @return the value of trade.u_id
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public String getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.u_id
     *
     * @param uId the value for trade.u_id
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.account
     *
     * @return the value of trade.account
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public BigDecimal getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.account
     *
     * @param account the value for trade.account
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public void setAccount(BigDecimal account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.t_date
     *
     * @return the value of trade.t_date
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public Date gettDate() {
        return tDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.t_date
     *
     * @param tDate the value for trade.t_date
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public void settDate(Date tDate) {
        this.tDate = tDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.state
     *
     * @return the value of trade.state
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.state
     *
     * @param state the value for trade.state
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.flag
     *
     * @return the value of trade.flag
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.flag
     *
     * @param flag the value for trade.flag
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}