package secondhandtrade.paltform.model;

import java.math.BigDecimal;

public class TradeDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_detail.t_id
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    private String tId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_detail.p_id
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    private String pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_detail.product_name
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_detail.product_price
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    private BigDecimal productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_detail.product_num
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    private Integer productNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_detail.flag
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_detail.t_id
     *
     * @return the value of trade_detail.t_id
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public String gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_detail.t_id
     *
     * @param tId the value for trade_detail.t_id
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public void settId(String tId) {
        this.tId = tId == null ? null : tId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_detail.p_id
     *
     * @return the value of trade_detail.p_id
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_detail.p_id
     *
     * @param pId the value for trade_detail.p_id
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_detail.product_name
     *
     * @return the value of trade_detail.product_name
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_detail.product_name
     *
     * @param productName the value for trade_detail.product_name
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_detail.product_price
     *
     * @return the value of trade_detail.product_price
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_detail.product_price
     *
     * @param productPrice the value for trade_detail.product_price
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_detail.product_num
     *
     * @return the value of trade_detail.product_num
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public Integer getProductNum() {
        return productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_detail.product_num
     *
     * @param productNum the value for trade_detail.product_num
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public void setProductNum(Integer productNum) {
        this.productNum = productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_detail.flag
     *
     * @return the value of trade_detail.flag
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_detail.flag
     *
     * @param flag the value for trade_detail.flag
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}