package secondhandtrade.paltform.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_id
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    private String uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.dormitory
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    private String dormitory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.b_no
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    private String bNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_id
     *
     * @return the value of user.u_id
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public String getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_id
     *
     * @param uId the value for user.u_id
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.dormitory
     *
     * @return the value of user.dormitory
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public String getDormitory() {
        return dormitory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.dormitory
     *
     * @param dormitory the value for user.dormitory
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public void setDormitory(String dormitory) {
        this.dormitory = dormitory == null ? null : dormitory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.b_no
     *
     * @return the value of user.b_no
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public String getbNo() {
        return bNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.b_no
     *
     * @param bNo the value for user.b_no
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    public void setbNo(String bNo) {
        this.bNo = bNo == null ? null : bNo.trim();
    }
}