package secondhandtrade.paltform.mapper;

import java.util.List;
import secondhandtrade.paltform.model.Bedroom;

public interface BedroomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bedroom
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    int deleteByPrimaryKey(String bNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bedroom
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    int insert(Bedroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bedroom
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    Bedroom selectByPrimaryKey(String bNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bedroom
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    List<Bedroom> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bedroom
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    int updateByPrimaryKey(Bedroom record);
}