package secondhandtrade.paltform.mapper;

import java.util.List;

import secondhandtrade.paltform.dto.ProductDTO;
import secondhandtrade.paltform.model.Product;
import secondhandtrade.paltform.vo.ProductVo;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    int deleteByPrimaryKey(String pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    Product selectByPrimaryKey(String pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    int updateByPrimaryKey(Product record);

    List<ProductVo> getProduct(ProductDTO productDTO);
}