package secondhandtrade.paltform.mapper;

import java.util.List;
import secondhandtrade.paltform.model.Product;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    int deleteByPrimaryKey(String pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    Product selectByPrimaryKey(String pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu May 17 21:51:15 CST 2018
     */
    int updateByPrimaryKey(Product record);
}