package secondhandtrade.paltform.mapper;

import java.util.List;
import secondhandtrade.paltform.model.Trade;

public interface TradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    int deleteByPrimaryKey(String tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    int insert(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    Trade selectByPrimaryKey(String tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    List<Trade> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    int updateByPrimaryKey(Trade record);
}