package secondhandtrade.paltform.mapper;

import java.util.List;

import secondhandtrade.paltform.dto.UserDTO;
import secondhandtrade.paltform.model.User;
import secondhandtrade.paltform.vo.UserVo;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    int deleteByPrimaryKey(String uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    User selectByPrimaryKey(String uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun May 20 19:42:41 CST 2018
     */
    int updateByPrimaryKey(User record);

    UserVo selectUserByIdAndPassword(UserDTO userDTO);
}